name: CD

on:
  schedule:
    #- cron: '0 2 * * *' # run at 2 AM UTC
    - cron:  '*/5 * * * *'
      
jobs:
  build:
    name: Deploy Release
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: release
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.date.outputs.date}}
          release_name: Release ${{steps.date.outputs.date}}
          draft: false
          prerelease: false
